spring-cloud/spring-cloud-kubernetes

README.md
Updated link that had wrong path for reload example
=> Fix for broken example link

spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/StandardPodUtils.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/StandardPodUtilsTest.java
A small start to #26!
Added a null check in StandardPodUtils, since an instance with a null Kube client would have limited usefulness and we should protect developers from a configuration error. If a developer decides not to use a KubernetesClient, they should probably implement the PodUtils interface and supply an alternate implementation instead of passing null to StandardPodUtils.
Holding off on additional tests for StandardPodUtils for now, since it will be tricky to simulate running inside a pod because of the file system checks, and we can't guarantee that the test is running outside of a pod.
=> Add null param check for StandardPodUtils and Unit test

pom.xml, spring-cloud-kubernetes-dependencies/pom.xml, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/README.md, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/pom.xml, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/main/java/org/springframework/cloud/kubernetes/examples/App.java, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/main/java/org/springframework/cloud/kubernetes/examples/HelloController.java, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/main/resources/application.properties, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/test/java/org/springframework/cloud/kubernetes/examples/HelloWorldIT.java, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/test/resources/arquillian.xml, spring-cloud-kubernetes-examples/pom.xml
This pull request adds an example which demonstrates a simple integration-test.
The test is using [arquillian cube for kubernetes](https://github.com/arquillian/arquillian-cube/blob/master/docs/kubernetes.adoc) to install the app in an isolated namesapce and then lookup and access the actual service (via portforwarding).
Note: The pull request introduces a snapshot dependency on arquillian-cube, but hopefully will be replaced with a released version shortly.
=> #26: First draft of integration tests example.

spring-cloud-kubernetes-examples/kubernetes-reload-example/pom.xml
- POM name is too long to setup the Deployment & Service kubernetes name as it will generate this error when populated by f-m-p plugin
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.28:deploy (default-cli) on project spring-cloud-kubernetes-example-reload: Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments. Message: Deployment.extensions "spring-cloud-kubernetes-" is invalid: metadata.name: Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com'). Received status: Status(apiVersion=v1, code=422, …
```
=> POM name is too long to setup the Deployment & Service kubernetes name

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java
I've spent a good time today trying to figure out the issue with my ConfigMap, turns out there was an error in the yaml data. I think it would be really helpful to print these errors. For example:
```2017-04-11 15:03:00 [main] WARN  o.s.c.k.c.ConfigMapPropertySource - Can't read configMap with name: [aether] in namespace:[jarjar]. Ignoring
org.yaml.snakeyaml.parser.ParserException: while parsing MappingNode
in 'reader', line 1, column 1:
server:
^
Duplicate key: hystrix
in 'reader', line 196, column 28:```
Cheers,
Michal
=> Print exception when configmap cannot be parsed

pom.xml, spring-cloud-kubernetes-zipkin/src/main/java/org/springframework/cloud/kubernetes/zipkin/ZipkinKubernetesAutoConfiguration.java
Update spring-cloud-netflix, spring-cloud-sleuth & commons to use RELEASE versions instead of SNAPSHOT. Fix #82
=> Update spring-cloud-* versions

pom.xml, spring-cloud-kubernetes-config/src/test/groovy/org/springframework/cloud/kubernetes/config/CoreTest.groovy, spring-cloud-kubernetes-dependencies/pom.xml, spring-cloud-kubernetes-ribbon/src/test/groovy/io/fabric8/spring/cloud/kubernetes/ribbon/test/RibbonTest.groovy
Update pom file to use 1.3.3.BUILD-SNAPSHOT of spring-cloud-build
- Pom file changed : spring-cloud-kubernetes-dependencies
- Pom file changed : spring-cloud-kubernetes
No SNASPHOT versions are now reported under sck-core
```
INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spring-cloud-kubernetes-core ---
[INFO] org.springframework.cloud:spring-cloud-kubernetes-core:jar:0.2.0.BUILD-SNAPSHOT
[INFO] +- io.fabric8:kubernetes-client:jar:2.2.0:compile
[INFO] |  +- io.fabric8:kubernetes-model:jar:1.0.67:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.7.5:compile
[INFO] |  |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.6.0:compile
[INFO] |  |  \- …
```
=> Update pom file to use 1.3.3.BUILD-SNAPSHOT of spring-cloud-build

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java
- Fix issue 106 and add support for active Profiles in order to select from the Config Map, the keys assigned to the active profile
- Example: When this config Map is loaded and if the POD is started with this JAV_OPTIONS param `java  -Dspring.profiles.active=production -jar /deployment/my-1.0.0.jar`, than you will get from the REST controller the greeting message `Say Hello to the Ops`
```
data:
application.yml: |-
greeting:
message: Say Hello to the World
---
spring:
profiles: development
greeting:
message: Say Hello to the Developers
---
spring:
profiles: production
greeting:
message: Say Hello to the Ops
```
=> Issue 106 - Support Active Profiles with YAML Config Map

spring-cloud-kubernetes-dependencies/pom.xml, spring-cloud-kubernetes-ribbon/pom.xml, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonFallbackTest.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonTest.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/TestApplication.java, spring-cloud-kubernetes-ribbon/src/test/resources/application.yml, spring-cloud-kubernetes-ribbon/src/test/resources/logback-test.xml
Add java test case covering Ribbon where 3 scenario are played.
- Register a kubernetes endpoint and call using Ribbon Client discovery the mock endpoint
- Unregister kubernetes endpoint and can't call the mock endpoint as the ribbon list is empty
- Re register again the kubernetes endpoint and call using Ribbon Client discovery the mock endpoint
=> Add java test case covering Ribbon where 3 scenario are played.

README.md, spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesAutoConfiguration.java
fixed typo in maven deps and added missing > in README.
=> Typo fixes in README.md and fixed wrong logger context in KubernetesAutoConfiguration

README.md
I've fixed the link to the 'Spring Cloud Circuitbreaker and Ribbon Example'
=> Fix link to circuitbreaker and ribbion example

spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileApplicationListener.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileApplicationListenerTest.java
First part of the `addKubernetesProfile` method executes the same logic as the second part, just without logging.
=> Remove duplicate logic from addKubernetesProfile

README.md, spring-cloud-kubernetes-config/pom.xml, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapConfigProperties.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/KubernetesPropertySource.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/SecretsPropertySource.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java
Allows making ConfigMaps available as spring properties from Kubernetes volumes, just like is currently possible with Secrets. This allows using ConfigMaps without resorting to environment variables or enabling extra permissions for service accounts. Seems this would offer a workaround/solution for #141, probably #138, #137 and #129.
See also the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume) on how to configure this on the Kubernetes side.
=> Allow ConfigMaps to be parsed from mounted volume paths, like Secrets

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java, spring-cloud-kubernetes-config/src/test/resources/application.properties, spring-cloud-kubernetes-config/src/test/resources/application.yaml
I have added support handling **ConfigMaps** specified via `spring.cloud.kubernetes.config.paths` that are build from `application.properties` or `application.yml `files.
Previously any content inside the paths were handled just like **Secrets** - the file would be a property name and the content of the file, it's value.
Now we check for the file name and in case it is an application config file it's parsed and the configs inside them are added instead.
This is the same functionality that was used when specifying **named** configs, it was just reused for configs specified via **paths**.
=> added support for ConfigMap built from files

README.md
It took me a while to find out why the discoveryClient did only return empty attributes (e.g. serviceList) .
Adding `@EnableDiscoveryClient` fixed this for me.
=> Add important documentation.

spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/LazilyInstantiateTest.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileApplicationListenerTest.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchTest.java
The old `org.mockito.runners.MockitoJUnitRunner` has been deprecated in
favor of `org.mockito.junit.MockitoJUnitRunner`
=> Change package of MockitoJUnitRunner

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesNoActiveProfileSpringBootTest.java
Before this fix, when a ConfigMap contained profiles but no active profile was set, then no data was read from the ConfigMap at all
=> Fix issue with ConfigMap with profiles inside and no active profiles

README.md
Close #147 
As @BarDweller pointed out, the documentation is not explicit enough.
This change makes the requirement for the `@EnableDiscoveryClient` annotation more obvious (especially since there is no error message hinting to this problem).
=> Make documentation for DiscoveryClient more explicit

README.md, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesNoActiveProfileSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithoutProfilesSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingController.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingProperties.java, spring-cloud-kubernetes-config/src/test/resources/application-with-profiles.yaml, spring-cloud-kubernetes-config/src/test/resources/application-without-profiles.yaml
With the current implementation, any default properties (i.e. part of yaml docs that did not specify a "spring.profile" entry) would not be read. This caused unexpected behavior where "default" keys were not being read, and if NO document specified a "spring.profile" entry, the configmap would be completely ignored.
This new logic instead performs yaml merge inheritance between any yaml doc that has no "spring.profile" entry, as well as docs with the specific "profile" we have active
=> Rework profile-based app.yaml parsing to support yaml merging

README.md, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java, spring-cloud-kubernetes-config/src/test/resources/adhoc.properties, spring-cloud-kubernetes-config/src/test/resources/adhoc.yml
When the ConfigMap contains a single entry, then the name of the file
does not have to application.(yaml|properties), but can be any
yaml/properties file.
This facilitates the use case where a confimap is created by something
like:
kubectl create configmap game-config --from-file=/path/app-config.yaml
=> Relax the name application.(yaml|properties) constraint in ConfigMap

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatch.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchTest.java
Fix problem [https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/150#issuecomment-402499289](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/150#issuecomment-402499289)
---
org.springframework.cloud.client.ServiceInstance  Instance is a Pod and not Service.
Pod name is [unique](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/)
---
P.S. Watch  resourceVersion  of EndpointsList not effective. Many false positives that do not affect the list of ServiceInstance.
=> KubernetesCatalogWatch endpoint based

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatch.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchTest.java
Fixes #223 by filtering null values that the k8s client can produce
=> 223: Fix issue with nullable targetRefs and addresses in endpoints

spring-cloud-kubernetes-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
#261 initial properties added. There are not too much hints that will help people with these properties. 
These properties are just propagating the configuration to the KubernetesClient.
=> Adding initial metadata for all the KubernetesConfigProperties

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryProperties.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientFilterMetadataTest.java
* Add flag to enable/disable addition of K8s Service ports to the
ServiceInstance metadata map (default: true).
* Add optional prefix to port keys in the metadata map
(default: "port.").
Fixes: gh-104
=> Add K8s Service ports as optional Service Metadata

README.adoc
fixed formatting of yaml source code example in lines 138-164. Also made source documentation consistent with [Asciidoctor reference guide](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code)
=> update bad formatting in README yaml examples

pom.xml, spring-cloud-kubernetes-discovery/pom.xml, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientBootstrapConfiguration.java, spring-cloud-kubernetes-discovery/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryAutoConfigurationTests.java
This patch enable kubernetes discovery client on bootstrap stage. So that it can works with `spring-cloud-config`
=> Enable kubernetes discovery client on bootstrap stage.

README.adoc, docs/src/main/asciidoc/property-source-config.adoc, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/PropertySourceUtils.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapTestUtil.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingController.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingProperties.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/ResponseMessage.java, spring-cloud-kubernetes-config/src/test/resources/application-path.yaml
This is done by removing the file walking and loading logic that existed
before and replacing it with an implementation that creates on
ConfigMapResource per specified path.
Reading and processing the content of the path is done in the exact
same way as the enableApi method does thus providing a consistent
experience.
The implementation is inspired by the following comment:
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/230#issuecomment-420341743
Fixes: #230
=> Rationalize ConfigMap usage when paths (mounted files) are involved

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java
The printed exception doesn't seem to add much except additional log output, i.e. (line numbers are due to being on 0.3.0):
```
java.lang.IllegalArgumentException: Name must be provided.
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:248)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:63)
at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.getData(ConfigMapPropertySource.java:85)
at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.<init>(ConfigMapPropertySource.java:66)
at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:77)```
```
The log message …
```
=> Remove exception from log when configMap can't be read

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesClientServicesFunction.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryProperties.java, spring-cloud-kubernetes-discovery/src/test/groovy/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.groovy, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientFilterTest.java
Arbitrary filtering of services is also possible by supplying a bean of
type `KubernetesClientServicesFunction`
This is an alternative to #308 and fixes #284
=> Add the ability to only discover services that match certain labels

docs/src/main/asciidoc/discovery-client.adoc, docs/src/main/asciidoc/getting-started.adoc, docs/src/main/asciidoc/ribbon-integration.adoc, docs/src/main/asciidoc/spring-cloud-kubernetes.adoc
List all starters in a summary near the beginning of the documentation.
Delete version from the example POM dependencies. Version should be
assigned by the BOM.
Fixes #146
Fixes #326
=> Document Spring Boot starters

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/PropertySourceUtils.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfileExpressionSpringBootTest.java, spring-cloud-kubernetes-config/src/test/resources/application-with-profiles.yaml
Spring Boot 2.1 introduced the ability to match profiles by [profile expression](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#profile-expression). For example, if a YAML document specifies
spring.profiles: production & us-east
then the properties from the document are loaded if both the `production` and `us-east` profiles are active.
=> Add profile expression support

mvnw, mvnw.cmd, pom.xml, spring-cloud-kubernetes-core/pom.xml, spring-cloud-kubernetes-dependencies/pom.xml, spring-cloud-kubernetes-discovery/pom.xml, spring-cloud-kubernetes-examples/kubernetes-circuitbreaker-ribbon-example/greeting-service/pom.xml, spring-cloud-kubernetes-examples/kubernetes-circuitbreaker-ribbon-example/name-service/pom.xml, spring-cloud-kubernetes-examples/kubernetes-circuitbreaker-ribbon-example/pom.xml, spring-cloud-kubernetes-examples/kubernetes-reload-example/pom.xml, spring-cloud-kubernetes-examples/kubernetes-zipkin-example/pom.xml, spring-cloud-kubernetes-examples/pom.xml, spring-cloud-kubernetes-leader/pom.xml, spring-cloud-kubernetes-ribbon/pom.xml, spring-cloud-starter-kubernetes-all/pom.xml, spring-cloud-starter-kubernetes-config/pom.xml, spring-cloud-starter-kubernetes-ribbon/pom.xml, spring-cloud-starter-kubernetes/pom.xml
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://cloud.spring.io migrated to:  
https://cloud.spring.io ([https](https://cloud.spring.io) result 200).
* http://www.apache.org/licenses/LICENSE-2.0 migrated to:  
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
* http://www.apache.org/licenses/LICENSE-2.0.txt migrated to:  
https://www.apache.org/licenses/LICENSE-2.0.txt ([https](https://www.apache.org/licenses/LICENSE-2.0.txt) result 200).
* http://www.spring.io migrated …
=> URL Cleanup

spring-cloud-kubernetes-examples/kubernetes-reload-example/README.md, spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/rb.yml, spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/role.yml, spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/sa.yml
1. Fixed small typos
2. Removed notes about Spring Boot liveness and readiness check related
to Fabric8 since that issue has been resolved and is working as expected
3. Added sample configuration files for K8s RBAC set up required for the
example to work
4. Added section about how to setup RBAC config
=> README update for ConfigMap reload sample

.circleci/config.yml
Needed because the checkstyle plugin could fail with older maven
versions
=> Use maven wrapper in integration tests

README.adoc, docs/src/main/asciidoc/ribbon-integration.adoc, spring-cloud-kubernetes-ribbon/pom.xml, spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesEndpointsServerList.java, spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesRibbonClientConfiguration.java, spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesRibbonMode.java, spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesRibbonProperties.java, spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesServerList.java, spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesServicesServerList.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonWithServiceModeTest.java
Enhanced Ribbon can support access to workloads through services while being compatible with Istio traffic policies
add `spring.cloud.kubernetes.ribbon.mode` configuration and the mode is enum
```java
public enum KubernetesRibbonMode {
/**
* using pod ip and port
*/
POD,
/**
* using kubernetes service name and port
*/
SERVICE
}
```
ServerList add server like this `httpbin.default.svc:8000`, and ribbon can access destination service
=> Enhanced Ribbon can support access to workloads through services 

spring-cloud-kubernetes-integration-tests/README.md
Show how Docker Desktop can be used instead of Microk8s to run tests
=> Update readme to include instructions for running tests on Mac & Windows

docs/src/main/asciidoc/discovery-client.adoc, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchAutoConfiguration.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.java, spring-cloud-kubernetes-discovery/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogServicesWatchConfigurationTest.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfigurationPropertiesTests.java
Needed in order to have that bean running in the correct application context when SC Config discovery is enabled.
Also fixes a bug where Kubernetes discovery was enabled when discovery was disabled with `spring.cloud.kubernetes.enabled=false`.
Relates to spring-cloud/spring-cloud-config#1229
=> Extracted catalog watch auto-configuration.

spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithActiveProfilesNameTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfileExpressionTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesNoActiveProfileTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithoutProfilesTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/CoreTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/HealthIndicatorTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/MultipleConfigMapsTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/MultipleSecretsTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/SecretsPropertySourceTest.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/HealthIndicatorTest.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/InfoContributorTest.java, spring-cloud-kubernetes-dependencies/pom.xml, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonFallbackTest.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonTest.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonWithServiceModeTest.java
This also requires bumping to Kubernetes client 4.4.x.
This changes is needed to make the tests pass with Java 11
=> Disable HTTP2 handling that causes an error in mock-webserver

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigurationChangeDetector.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/reload/EventBasedConfigurationChangeDetectorTests.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesServiceInstanceTests.java
The changes to how we add PropertySources in the bootstrap phase made in Spring Cloud Commons, broke the logic in config map reload https://github.com/spring-cloud/spring-cloud-commons/pull/652
These changes now account for that.
Fixes #524
=> Account For ConfigMapPropertySources Wrapped In BootstrapPropertySources

pom.xml
Related to issue #532 when building a sample project with `mvn clean package fabric8:deploy -Pkubernetes` but showing a different error of bad resource versions in the generated manifest files.
=> upgrade fabric8 plugin version from 3.5.37 to 4.4.0 fixes gh-532

spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileEnvironmentPostProcessor.java
This patch closes the connection pool of the ad-hoc kubernetes client for profile detection. This connection pool is unused after running the `KubernetsProfileEnvironmentPostProcessor`. And also, this PostProcessor may be called multiple times. This patch will prevent unnecessary connection pools from increasing.
=> Close the connection of ad hoc kubernetes client

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/PropertySourceUtils.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java
implementing PR #554 on 1.1.x branch
Issue: properties bound to a java.util.Map object do not maintain their
definition order and their values lose their data-type, since they 're
converted to String values.
This fix mainly targets org.springframework.cloud.kubernetes.config
.PropertySourceUtils.PROPERTIES_TO_MAP implementation: Configuration
properties that are bound to a java.util.Map had their value's type
affected by the use of .toString() on each entry's value during Map
entry processing. Moreover, the use of java.util.stream
.Collectors.toMap(java.util.function.Function<? super T,? extends K>,
java.util.function.Function<? super T,? extends U>) when processing
Map-bound properties, resulted in losing the entry insertion order of
the original Map. The fix entails usage of the …
=> Fix value data-type & entry-set order of yml properties bound to Map

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatch.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchAutoConfiguration.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchTest.java
Relates to #428 #448 #465 
**Type of request**
Bug fix
**Behavior**
When 
- the property `spring.cloud.kubernetes.discovery.all-namespaces` is true 
- and `@EnableScheduling` has been set
the service/pod discovery never see any addition/deletion of pods for a given service in a different namespace that the one the spring boot admin server is in.
**How to reproduce**
1. In a namespace `A`, deploy a spring boot application (deployment and service) with one replica
2. In a namespace `B`, deploy a spring boot admin server with the following annotations (as per the documentation of this project) :
`@SpringBootApplication
@EnableAdminServer
@EnableDiscoveryClient
@EnableScheduling`, the property `spring.cloud.kubernetes.discovery.all-namespaces` set to true (and the required rbac configuration) …
=> Fix scheduled discovery when allNamespaces property is true

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/PropertySourceUtils.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java
Issue: properties bound to a java.util.Map object do not maintain their
definition order and their values lose their data-type, since they 're
converted to String values.
This fix mainly targets org.springframework.cloud.kubernetes.config
.PropertySourceUtils.PROPERTIES_TO_MAP implementation: Configuration
properties that are bound to a java.util.Map had their value's type
affected by the use of .toString() on each entry's value during Map
entry processing. Moreover, the use of java.util.stream
.Collectors.toMap(java.util.function.Function<? super T,? extends K>,
java.util.function.Function<? super T,? extends U>) when processing
Map-bound properties, resulted in losing the entry insertion order of
the original Map. The fix entails usage of the original entry value and
a …
=> Fix value data-type & entry-set order issues of properties bound to Map

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadDefaultAutoConfiguration.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/EventBasedConfigMapChangeDetector.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/EventBasedSecretsChangeDetector.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/PollingConfigMapChangeDetector.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/PollingSecretsChangeDetector.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/condition/EventReloadDetectionMode.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/condition/PollingReloadDetectionMode.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/KubernetesConfigConfigurationTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/reload/EventBasedConfigurationChangeDetectorTests.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/BusEventBasedConfigMapWatcherChangeDetector.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/BusEventBasedSecretsWatcherChangeDetector.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/ConfigMapWatcherChangeDetector.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/ConfigurationWatcherAutoConfiguration.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/HttpBasedConfigMapWatchChangeDetector.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/HttpBasedSecretsWatchChangeDetector.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/SecretsWatcherChangeDetector.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/test/java/org/springframework/cloud/kubernetes/configuration/watcher/BusEventBasedConfigMapWatcherChangeDetectorTests.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/test/java/org/springframework/cloud/kubernetes/configuration/watcher/BusEventBasedSecretsWatcherChangeDetectorTests.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/test/java/org/springframework/cloud/kubernetes/configuration/watcher/HttpBasedConfigMapWatchChangeDetectorTests.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/test/java/org/springframework/cloud/kubernetes/configuration/watcher/HttpBasedSecretsWatchChangeDetectorTests.java
…ge detectors each for reload detection mode event/polling. Fixes #643
1. Adds a changeDetector each for configMaps/Secrets and event/polling modes
2. Moves reload mode conditionals into a sub package, usable by both autoConfiguration and defaults
3. Additional tests
4. updates to logging to indicate event/polling watcher activation
=> Refactor ConfigurationChangeDetector to simplify conditionals. Issue 643

spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/profile/KubernetesClientProfileEnvironmentPostProcessor.java, spring-cloud-kubernetes-client-autoconfig/src/test/java/org/springframework/cloud/kubernetes/client/profile/KubernetesClientProfileEnvironmentPostProcessorTests.java, spring-cloud-kubernetes-fabric8-autoconfig/src/main/java/org/springframework/cloud/kubernetes/fabric8/profile/Fabric8ProfileEnvironmentPostProcessor.java, spring-cloud-kubernetes-fabric8-autoconfig/src/test/java/org/springframework/cloud/kubernetes/fabric8/profile/Fabric8ProfileEnvironmentPostProcessorTests.java
When the KUBERNETES_SERVICE_HOST environment variable is defined, the "kubernetes" profile is enabled, even if Spring cannot access the Kubernetes API.
Fixes gh-656
=> Enable the kubernetes profile without API requests

README.adoc, docs/src/main/asciidoc/getting-started.adoc
I updated some invalid anchors in the docs and generated README.adoc via `./mvnw install -P docs`
=> Update anchors for docs

docs/src/main/asciidoc/spring-cloud-kubernetes.adoc
It was likely just a copy & paste mistake.
=> Change "Sleuth" to "Kubernetes" in the reference

pom.xml, spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/KubernetesClientAutoConfiguration.java, spring-cloud-kubernetes-client-discovery/pom.xml, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/ConditionalOnKubernetesDiscoveryEnabled.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesDiscoveryClientConfigClientBootstrapConfiguration.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesDiscoveryProperties.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClient.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesReactiveDiscoveryClientAutoConfiguration.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesServiceInstance.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/gson/EndpointsTrimmingStrategy.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/gson/ServiceTrimmingStrategy.java, spring-cloud-kubernetes-client-discovery/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesDiscoveryClientConfigClientBootstrapConfigurationTests.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClientTests.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesReactiveDiscoveryClientAutoConfigurationTests.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesServiceInstanceTests.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/gson/EndpointsTrimmingStrategyTests.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/gson/ServiceTrimmingStrategyTests.java, spring-cloud-kubernetes-dependencies/pom.xml, spring-cloud-kubernetes-integration-tests/discovery/kubernetes-client-discovery/pom.xml, spring-cloud-kubernetes-integration-tests/discovery/kubernetes-client-discovery/src/main/fabric8/deployment.yml, spring-cloud-kubernetes-integration-tests/discovery/kubernetes-client-discovery/src/main/fabric8/svc.yml, spring-cloud-kubernetes-integration-tests/discovery/kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/it/DiscoveryClientApplication.java, spring-cloud-kubernetes-integration-tests/discovery/pom.xml
this will be disabled by default unelss you toggle on the `spring.cloud.kubernetes.discovery.informer.enabled` bit
=> Feat: Adding an informer-based discovery client to read instances from cache

spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/LazilyInstantiate.java
These are the overall changes:
- No need for `T`, type inference will work.
- The fact that `get` is `synchronized` implies that an instance of this class can be called concurrently, which implies that it must be safely published. But that is not the case. A correctly published instance (strictly speaking about immutable classes), must have _all_ fields final. This is required by the JLS.
Under the current implementation (I have checked `java-8` to `16`), all implementations insert proper barriers even if a _single_ field is final, i.e.:
```
private LazilyInstantiate(Supplier<T> supplier) {
this.supplier = supplier;
this.current = this::swapper;
// proper barriers are here even if current is not final
}
```
But there are no guarantees that this will stay the same in future versions, it …
=> improvments on lazy instance

docs/src/main/asciidoc/discovery-client.adoc, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryProperties.java
Discovering "not-ready" service endpoints will help tools like Spring Boot Admin continue to monitor all endpoints, ready or not.
Should resolve https://github.com/spring-cloud/spring-cloud-kubernetes/issues/584
=> Allow opt-in for discovering "not-ready" service endpoints

spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClient.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClientTests.java
If a subset of an endpoint doesn't have any (ready) addresses the K8s client returns `null` when retrieving them, which results in a NPE when attempting to map an address to a `KubernetesServiceInstance`.
=> Catch NPE when subset has no (ready) addresses

spring-cloud-kubernetes-dependencies/pom.xml
org.springframework.cloud:spring-cloud-kubernetes-test-support dependency moved to Testing Dependencies section and scope test added
What about com.squareup.okhttp3 dependencies defined in Testing Dependencies section, should they have the test scope too?
=> spring-cloud-kubernetes-test-support dependency moved to Testing Dependencies section and scope test added

spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesServicesServerList.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/KubernetesServiceServerListTest.java
fix a bug when there are more than one ports in a k8s service.
for example, if there are 2 ports in my service, one for the tomcat named default, one for other purpose named other
The request can be only send to the default port.
so, I have a config 'ribbon.PortName=default' which will be set in the KubernetesServerList.portName.
In the origin code, 'Utils.isNotNullOrEmpty(this.getPortName())' means once I have this config, all ports will be add to the KubernetesServicesServerList.
so what I set in the ribbon.PortName has no effects.
Changing 'Utils.isNotNullOrEmpty(this.getPortName())'  to  'Utils.isNullOrEmpty(this.getPortName())' will fix that.
Only the portName match what I set in config will be added to the ServerList.
=> fix a bug when there are more than one ports

README.adoc, docs/src/main/asciidoc/spring-cloud-kubernetes-configuration-watcher.adoc
The previous links are broken.
=> Fixing dockerhub links in docs and Readme

spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/Constants.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/PropertySourceUtils.java, spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/PropertySourceUtilsTest.java
Support property 'spring.config.activate.on-profile' introduced with Spring Boot 2.4
Fixes #778
=> #778 Support property 'spring.config.activate.on-profile'.

docs/src/main/asciidoc/security-service-accounts.adoc
- The resource requirements listed by component are all members of the
core API group. There is no need to include the `extensions` and
`apps` groups. This Role will currently try to grant permissions on
types that do not exist, such a `pod.extensions` and `pod.apps`.
- If you are a member of a multitenant cluster, there's a good chance
that you are running with either the `admin` or `edit` built-in
Clusterroles scoped down to your namespace(s). Since certain types
such as `pod.extensions` do not exist, your binding to a built-in Role
will not contain permissions on these types. As such, you will get a
permission error when trying to create the Role (trying to grant
permissions you do not hold). The Role as written could only currently
be created in a cluster by someone who has a higher …
=> Remove unnecessary API groups in sample Role

spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesDiscoveryClientAutoConfiguration.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClient.java, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/SpringCloudKubernetesInformerFactoryProcessor.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClientTests.java
Fixes #810
This also fixes a problem where `KubernetesDiscoveryClient` was being initialized too early and properties were not being bound.
=> Add support for filtering by service-labels to Informer based DiscoveyClient

spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigUtils.java
The `WARN` log level is being abused here which can flood the production logs (usually you are not interested in any lower log levels there). It is totally fine to not define a separate configMap for each profile that is active in the application therefore it shouldn't be a warning. The same applies to any other form of externalized configuration.
=> Change the log level to prevent false-positives

spring-cloud-kubernetes-client-config/pom.xml, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientRetryBootstrapConfiguration.java, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/RetryableKubernetesClientConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/RetryableKubernetesClientSecretsPropertySourceLocator.java, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientEventBasedConfigMapChangeDetector.java, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientEventBasedSecretsChangeDetector.java, spring-cloud-kubernetes-client-config/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/EnableRetryBootstrapConfiguration.java, spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapPropertySourceLocatorRetryTests.java, spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientSecretsPropertySourceLocatorRetryTests.java, spring-cloud-kubernetes-client-config/src/test/resources/META-INF/spring.factories, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SecretsPropertySourceLocator.java, spring-cloud-kubernetes-fabric8-config/pom.xml, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8RetryBootstrapConfiguration.java, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/RetryableFabric8ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/RetryableFabric8SecretsPropertySourceLocator.java, spring-cloud-kubernetes-fabric8-config/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/EnableRetryBootstrapConfiguration.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigMapPropertySourceLocatorRetryTests.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8SecretsPropertySourceLocatorRetryTests.java, spring-cloud-kubernetes-fabric8-config/src/test/resources/META-INF/spring.factories
Fixes #963
This fix removes the `@Retryable` annotations from the `abstract` `PropertySourceLocator`s and puts them on specific instances that will be used as beans when we want the retry behavior enabled.  It is mostly just autoconfiguration changes at the end of the day and little in the way of functional changes.
=> Move @retryable annotations to separate beans

pom.xml, spring-cloud-kubernetes-integration-tests/pom.xml
Eclipse JKube 1.6.0 was just released: https://github.com/eclipse/jkube/releases/tag/v1.6.0
- Bump Kubernetes Maven Plugin version
- Remove base image override (it's the same as the current default)
=> deps: bump JKube to 1.6.0

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/DiscoveryServerUrlInvalidException.java
I saw a discrepancy between this Discovery Server URL exception and the actual path prefix for the Kubernetes Discovery  properties. This PR updates the exception message so it matches the path.
```java
@ConfigurationProperties("spring.cloud.kubernetes.discovery")
public class KubernetesDiscoveryClientProperties {
private String discoveryServerUrl;
...
}
```
**Commits:**
* Updates `DiscoveryServerUrlInvalidException` message with appropriate property path.
=> Discovery Server URL exception message fix

docs/src/main/asciidoc/_configprops.adoc, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/leader/LeaderProperties.java, spring-cloud-kubernetes-fabric8-leader/src/main/java/org/springframework/cloud/kubernetes/fabric8/leader/Fabric8LeadershipController.java, spring-cloud-kubernetes-fabric8-leader/src/test/java/org/springframework/cloud/kubernetes/fabric8/leader/Fabric8LeadershipControllerTest.java
As configmaps are sometimes managed by different parties (in our case it is a Helmchart that takes care of creating and destroying configmaps), it would be helpful to have a possibility to disable leader configmap creation on the library's side.
=> Add possibility to disable configmap creation

spring-cloud-kubernetes-examples/kubernetes-reload-example/pom.xml
There are 1 security vulnerabilities found in org.hibernate:hibernate-validator 5.3.6.Final
- [CVE-2019-10219](https://www.oscs1024.com/hd/CVE-2019-10219)
Upgrade org.hibernate:hibernate-validator from 5.3.6.Final to 6.0.19.Final for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` failed locally, couldn't complete the build process.
Run `mvn clean test` failed locally, unit-test couldn't pass.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.hibernate:hibernate-validator to 6.0.19.Final

spring-cloud-kubernetes-commons/pom.xml
There are two `spring-boot-starter-logging dependencies` in `spring-cloud-kubernetes-commons`，We could remove one
=> Remove redundant dependencies

docs/src/main/asciidoc/property-source-config.adoc
Just something I came across whilst reading the documentation. Caused by asciidoctor/asciidoctor#1514
=> minor fix in property-source-config.adoc for proper escaping of code style

spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientSecretsCache.java, spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientSecretsPropertySourceTests.java
If the secret contains no data the `transform` method will throw a NPE.  This exception gets caught but the name generation of the secret is incorrect.
=> Check for empty data in secret

spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientSecretsPropertySourceLocator.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/ConfigDataRetryableSecretsPropertySourceLocator.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SecretsPropertySourceLocator.java, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8SecretsPropertySourceLocator.java
This PR replaces the use of Spring Framework's `MapPropertySource` with Spring Cloud's `SecretsPropertySource` (which extends `MapPropertySource`). This is semantically clearer and allows users to sanitize secrets based on their property source class.
=> Use SecretsPropertySource for Kubernetes secrets

spring-cloud-kubernetes-commons/pom.xml
This fixes #870 . It makes `spring-boot-starter-logging` optional.
=> fix issue 870 - make spring-boot-starter-logging optional

spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configserver/src/main/java/org/springframework/cloud/kubernetes/configserver/KubernetesEnvironmentRepository.java, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configserver/src/test/java/org/springframework/cloud/kubernetes/configserver/KubernetesEnvironmentRepositoryTests.java
The properties defined by the configmap "application" should be the last in the environment list, so you can always override the properties values by profile and by application
=> Fix properties retrieval order from configmaps

spring-cloud-kubernetes-fabric8-discovery/pom.xml
Fixes #1363.  Pretty self-explanatory otherwise.
=> #1363: make Mockito dependency test-scoped instead of compile-scoped

docs/src/main/asciidoc/property-source-config.adoc
This commit updates the property-source-config.adoc to clarify the need to escape the "kubernetes:" value for the 'spring.config.import' property.
=> Clarify k8s ConfigMap property source instructions

docs/modules/ROOT/pages/spring-cloud-kubernetes-discoveryserver.adoc
tried the docs, which drifted a bit.
Note: My brain broke about why this is using the same port as eureka. It seems it was an arbitrary choice, not a transition story. So, I didn't document anything about that.
=> discoveryserver: fixes deployment yaml and adds notes about use of Eureka's port

docs/modules/ROOT/pages/spring-cloud-kubernetes.adoc, pom.xml
The former process is too easy to forget and doesn't error either.
=> Replaces manual workaround for Paketo with Maven profile

spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-istio/src/test/java/org/springframework/cloud/kubernetes/fabric8/client/istio/Fabric8IstioIT.java, spring-cloud-kubernetes-test-support/src/main/java/org/springframework/cloud/kubernetes/integration/tests/commons/Commons.java, spring-cloud-kubernetes-test-support/src/main/java/org/springframework/cloud/kubernetes/integration/tests/commons/fabric8_client/Util.java
=> Ensures istio/istioctl is pulled locally prior to use

docs/modules/ROOT/pages/spring-cloud-kubernetes-configserver.adoc, spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configserver/pom.xml
- Add Maven profile `useVault` which adds Spring Vault Core dependency to enable Vault integration in the Spring Cloud Kubernetes Config Server.
=> Add Maven profile for Vault integration

spring-cloud-kubernetes-fabric8-autoconfig/pom.xml, spring-cloud-kubernetes-fabric8-leader/pom.xml
This is needed since Spring Boot no longer manages the version.  The version is managed in Spring Cloud Commons.  See https://github.com/spring-cloud/spring-cloud-commons/pull/1470. Fixes #1813
=> Specify okhttp dependency

spring-cloud-kubernetes-controllers/pom.xml
Fix for #1456
Added a classifier for the 'repackage' execution defined here and also for the 'default' execution defined in the spring-cloud-build parent pom.
New PR agains branch 3.1.x as suggested in #1888
=> Keep the original JAR when repackaging (#1456)

docs/modules/ROOT/pages/property-source-config/configmap-propertysource.adoc
The link to [ConfigMap](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#configmap-propertysource) is outdated in the doc.
* Update the link with the correct one.
=> Update ConfigMap link in Documentation

spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/reactive/KubernetesInformerReactiveDiscoveryClientAutoConfigurationApplicationContextTests.java
When the isEqualTo assertion is not met, the error message only states that the value was something other than 2. When the hasSize assertion is not met, the error message includes the contents of the map. This makes it easier to determine what's missing.
=> Improve assertions

spring-cloud-kubernetes-client-autoconfig/src/test/java/org/springframework/cloud/kubernetes/client/ActuatorEnabledFailFastExceptionTest.java, spring-cloud-kubernetes-client-autoconfig/src/test/java/org/springframework/cloud/kubernetes/client/ActuatorEnabledNoFailFastExceptionTest.java
Mocking `Paths` completely caused some methods to return `null` which breaks Netty's `io.netty.util.internal.PlatformDependent`. Using `CALLS_REAL_METHODS` narrows the effects of the mocking as any methods calls without expectations now call the real methods instead of returning `null`.
=> Narrow scope of static mocking that breaks Netty 4.2

docs/modules/ROOT/pages/discovery-client.adoc, docs/modules/ROOT/pages/getting-started.adoc, docs/modules/ROOT/pages/kubernetes-awareness.adoc, docs/modules/ROOT/pages/property-source-config/configmap-propertysource.adoc, docs/modules/ROOT/pages/property-source-config/propertysource-reload.adoc
Fixed some broken links in documents and replaced tabs with spaces in some yaml sources, with adding yaml syntax highlighting.
There are more broken links, but I couldn't find appropriate link for them.
=> Fix broken docs and polish
