spring-cloud/spring-cloud-kubernetes

pom.xml
This is not meant to be merged, at least not yet.
=> #36: Remove bom generation

spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/LazilyInstantiate.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/LazilyInstantiateTest.java
=> #26: Create unit test for LazilyInstantiate

spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/test/resources/logback-test.xml
Add logback-test.xml file to change the logging level of hibernate validator to info. Fix #53
=> Add logback-test.xml file to change the logging level of hibernate validator

spring-cloud-kubernetes-examples/kubernetes-hello-world-example/pom.xml, spring-cloud-kubernetes-examples/kubernetes-reload-example/pom.xml
- Add dc.yaml file under src/main/fabric8 to fix the docker image to use as version latest. In this case, the docker image will be found.
- Fix #55
=> Add dc.yaml file 

spring-cloud-kubernetes-examples/kubernetes-hello-world-example/README.md
Add profile kubernetes for local build/deployment on minikube and avoid CI build failure if the goal build is included within the f-m-p configuration section
=> Add profile kubernetes for local build/deployment on minikube

spring-cloud-kubernetes-examples/kubernetes-hello-world-example/pom.xml
Add the NodePort service type using enricher section of the f-m-p config
=> Define service type using enricher section of the f-m-p config

README.md
=> Updated links for "... Spring Boot - Ribbon"

spring-cloud-kubernetes-config/pom.xml, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsSpringBootTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/App.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/Greeting.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingController.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingProperties.java, spring-cloud-kubernetes-config/src/test/resources/logback-test.xml, spring-cloud-kubernetes-dependencies/pom.xml
=> Add a more real Java testcase

spring-cloud-kubernetes-examples/kubernetes-circuitbreaker-ribbon-example/greeting-service/src/main/resources/application.yml, spring-cloud-kubernetes-examples/kubernetes-circuitbreaker-ribbon-example/readme.md
- Change ServerListRefreshInterval and Hystrix timeoutInMilliseconds.
- Fix typo error within the README file
=> Change ServerListRefreshInterval and Hystrix timeoutInMilliseconds

README.md
=> Obvious Fix: PostgreSQL secret: typo and copy/paste error

spring-cloud-kubernetes-dependencies/pom.xml
Update kube lib to be aligned with version used by  s-c-dataflow-server-kubernetes /  s-c-deployer-kubernetes projects
Fix #108
=> Update kubernetes client lib

README.md
Review content of the README file to correct mistakes, improve content, add missing stuffs
=> Review README file.

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapTestUtil.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesSpringBootTest.java, spring-cloud-kubernetes-config/src/test/resources/application-with-profiles.yaml
=> Fix ConfigMap with profiles functionality

circle.yml, spring-cloud-kubernetes-ribbon/pom.xml, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonFallbackTest.java
=> Fix flaky ribbon test

spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeaderAutoConfiguration.java
https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/202
=> Don't start LeaderInitiator when creating a bean

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatch.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchTest.java
=> 238: Fix issue with nullable subsets in endpoints

spring-cloud-kubernetes-config/pom.xml, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/HealthIndicatorTest.java, spring-cloud-kubernetes-core/pom.xml, spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesAutoConfiguration.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/HealthIndicatorTest.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/example/App.java
=> Fix issue where Kubernetes specific info did not show up in /health

pom.xml, spring-cloud-kubernetes-config/pom.xml, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/MissingActuatorTest.java, spring-cloud-kubernetes-examples/kubernetes-hello-world-example/pom.xml
=> Make reload config conditional on the presense of the actuator

spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesAutoConfiguration.java, spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesClientProperties.java
=> Add proxy properties for the Kubernetes client configuration

spring-cloud-kubernetes-examples/kubernetes-zipkin-example/README.md
=> Fix pvc template in README 

docs/src/main/asciidoc/discovery-client.adoc, docs/src/main/asciidoc/examples.adoc, docs/src/main/asciidoc/kubernetes-awareness.adoc, docs/src/main/asciidoc/leader-election.adoc, docs/src/main/asciidoc/other-resources.adoc, docs/src/main/asciidoc/pod-health-indicator.adoc, docs/src/main/asciidoc/property-source-config.adoc, docs/src/main/asciidoc/ribbon-integration.adoc, docs/src/main/asciidoc/security-service-accounts.adoc
Fixes #268 and add documentation examples and resources
=> Doc improvements and fix 268

spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeadershipController.java, spring-cloud-kubernetes-leader/src/test/java/org/springframework/cloud/kubernetes/leader/LeadershipControllerTest.java
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/296
=> Fix NPE when local leader is null

spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesAutoConfiguration.java, spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesInfoContributor.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/InfoContributorTest.java
Resolves #128.
This initial implementation is a clone of the Health indicator details. Happy to make changes or augment with anything else that might be useful.
=> Add InfoContributor reporting pod details

README.adoc, docs/src/main/asciidoc/property-source-config.adoc
@geoand from https://github.com/spring-cloud/spring-cloud-kubernetes/pull/328
=> ~Updated docs. Added notes about changed behavior of paths property

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java
"the object argument `must be` null" should be "the object argument `must not be` null"
=> Assert message "must be null" chnaged to "must not be null"

spring-cloud-kubernetes-core/pom.xml, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/HealthIndicatorTest.java, spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/InfoContributorTest.java, spring-cloud-kubernetes-leader/pom.xml, spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeaderAutoConfiguration.java, spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeaderInfoContributor.java, spring-cloud-kubernetes-leader/src/test/java/org/springframework/cloud/kubernetes/leader/LeaderAutoConfigurationTests.java, spring-cloud-kubernetes-leader/src/test/java/org/springframework/cloud/kubernetes/leader/LeaderInfoContributorTest.java
=> Add info contributor for leader election.

docs/src/main/asciidoc/property-source-config.adoc
=> Fix code snippets in PropertySource config docs

README.adoc
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
=> document reloader dependency on actuator-autoconfigure

docs/pom.xml, docs/src/main/asciidoc/discovery-client.adoc, docs/src/main/asciidoc/discovery-kubernetes-native.adoc, docs/src/main/asciidoc/examples.adoc, docs/src/main/asciidoc/kubernetes-awareness.adoc, docs/src/main/asciidoc/other-resources.adoc, docs/src/main/asciidoc/pod-health-indicator.adoc, docs/src/main/asciidoc/property-source-config.adoc, docs/src/main/asciidoc/ribbon-integration.adoc, docs/src/main/asciidoc/security-service-accounts.adoc, docs/src/main/asciidoc/spring-cloud-kubernetes.adoc
I edited for spelling, punctuation, grammar, usage, and corporate voice. I also corrected some links and made sure everything points uses https rather than http.
=> Editing pass

.circleci/config.yml, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadProperties.java, spring-cloud-kubernetes-integration-tests/discovery/tests/src/test/java/org/springframework/cloud/kubernetes/it/ServicesIT.java, spring-cloud-kubernetes-integration-tests/istio/src/test/java/org/springframework/cloud/kubernetes/it/ProfilesIT.java, spring-cloud-kubernetes-integration-tests/pom.xml, spring-cloud-kubernetes-integration-tests/simple-configmap/src/test/java/org/springframework/cloud/kubernetes/it/GreetingIT.java, spring-cloud-kubernetes-integration-tests/simple-core/src/test/java/org/springframework/cloud/kubernetes/it/GreetingAndHealthIT.java
=> Ensure that instances don't restart at the same time upon config change

docs/pom.xml
I tossed out dependencies we don't need once we start using spring-doc-resources.
NOTE: This PR depends on spring-cloud/spring-cloud-build#84
DO NOT merge this one until that one is merged.
=> Modernizing the docs pom

README.adoc, docs/src/main/asciidoc/property-source-config.adoc
i have updated the paragraph as discussed, but also i have modified the resource yaml file to be general I've used a POD, any suggestions !
=> Enhance docs about setting Spring profile at bootstrap via ENV Variable 

README.adoc, docs/src/main/asciidoc/property-source-config.adoc, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithActiveProfilesNameSpringBootTest.java, spring-cloud-kubernetes-config/src/test/resources/application-with-active-profiles-name.yaml
Based on #153 this pull request will search and fetch configMap names with active profiles.
fixes gh-153
=> Search configMap with active profile name.

.gitignore, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedSpringBootTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithActiveProfilesNameTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfileExpressionTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesNoActiveProfileTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithoutProfilesTests.java, spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/MultipleConfigMapsTests.java
cc @spencergibb  
first change, waiting for approval  
files changed::
`ConfigMapsFromFilePaths`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsTests.java)
`ConfigMapsMixed`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master//spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedSpringBootTest.java) | …
=> rename *SpringBootTest to *IntegrationTests or just *Tests

spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileEnvironmentPostProcessor.java
=> Make Post Processor honor spring.cloud.kubernetes.enabled

spring-cloud-kubernetes-config/pom.xml, spring-cloud-kubernetes-core/pom.xml, spring-cloud-kubernetes-dependencies/pom.xml
Needed in order to build the project in Java 11
Fixes: #432
=> Exclude tools java from dependencies

spring-cloud-kubernetes-dependencies/pom.xml
Needed to get the build working with Java 11
=> Bump mockwebserver version

docs/src/main/asciidoc/security-service-accounts.adoc
This Pull Request adds documentation on custom roles (see #439 for more information)
=> #439: Add custom role definition

docs/src/main/asciidoc/kubernetes-awareness.adoc
Clarify disabling Kubernetes features #510
=> Clarify disabling Kubernetes features

spring-cloud-kubernetes-examples/kubernetes-hello-world-example/README.md, spring-cloud-kubernetes-examples/kubernetes-leader-election-example/README.md, spring-cloud-kubernetes-examples/kubernetes-reload-example/README.md
In the README file, display the short link properly for the minikube
=> Reformat README file

spring-cloud-kubernetes-dependencies/pom.xml
upgrading fabric8 client from 4.4.1 to 4.9.0 and Istio client from 1.0.0 to 1.1.1 fixes gh-515
=> upgrading fabric8 and Istio clients version

spring-cloud-kubernetes-core/src/main/resources/META-INF/spring.factories
Spring factories failing to load the class because of extra spaces
=> Remove extra space

spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatch.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchAutoConfiguration.java, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchTest.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientFilterMetadataTest.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.java
to filter discovered services with labels.
fixes gh-473
=> discovered services filtered by labels fixes gh-473

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigurationChangeDetector.java, spring-cloud-kubernetes-dependencies/pom.xml, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/reactive/KubernetesReactiveDiscoveryClientTests.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonFallbackTest.java, spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonTest.java
=> Upgrade k8s client

spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/ConfigurationWatcherAutoConfiguration.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/src/test/java/org/springframework/cloud/kubernetes/client/config/it/ConfigMapAndSecretIT.java
Refactor config watcher to resolve conflicts upon merge to master.
=> fix conflicts upon merge

spring-cloud-kubernetes-integration-tests/run.sh, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/src/test/java/org/springframework/cloud/kubernetes/client/config/it/ConfigMapAndSecretIT.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/src/test/resources/spring-cloud-kubernetes-client-config-it-deployment.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/src/test/resources/spring-cloud-kubernetes-client-config-it-polling-deployment.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/java/org/springframework/cloud/kubernetes/configuration/watcher/ActuatorRefreshIT.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/java/org/springframework/cloud/kubernetes/configuration/watcher/ActuatorRefreshKafkaIT.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/java/org/springframework/cloud/kubernetes/configuration/watcher/ActuatorRefreshRabbitMQIT.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/resources/spring-cloud-kubernetes-configuration-watcher-bus-amqp-deployment.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/resources/spring-cloud-kubernetes-configuration-watcher-bus-kafka-deployment.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/resources/spring-cloud-kubernetes-configuration-watcher-http-deployment.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/resources/spring-cloud-kubernetes-configuration-watcher-it-bus-amqp-deployment.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/src/test/resources/spring-cloud-kubernetes-configuration-watcher-it-bus-kafka-deployment.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-core-k8s-client-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-core-k8s-client-it/src/test/java/org/springframework/cloud/kubernetes/core/k8s/it/ActuatorEndpointIT.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-core-k8s-client-it/src/test/resources/spring-cloud-kubernetes-core-k8s-client-it-deployment.yaml
=> Removing local registry from the integration scripts

spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/KubernetesClientProperties.java, spring-cloud-kubernetes-commons/src/main/resources/META-INF/additional-spring-configuration-metadata.json, spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesAutoConfiguration.java
=> Adds support for oauthToken Issue #659

spring-cloud-kubernetes-client-config/pom.xml
test scope added at spring-cloud-kubernetes-test-support dependency in spring-cloud-kubernetes-client-config/pom.xml
=> #751 test scope added at spring-cloud-kubernetes-test-support dependency

docs/src/main/asciidoc/discovery-client.adoc, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClient.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClientTests.java, spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClient.java, spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClientTest.java
=> Use the "primary-port-name" label to discover ports

spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigurationChangeDetector.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/EventBasedConfigurationChangeDetector.java
Added debug logging of property source information
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/753
=> Issue-753 Add Debug Logging To ConfigurationChangeDetector

spring-cloud-kubernetes-config/pom.xml, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java, spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/PollingConfigurationChangeDetector.java
=> Remove @EnableAsync and @EnableScheduling to avoid conflicts.

spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientConfigReloadAutoConfiguration.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/reload/ConfigReloadAutoConfiguration.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/reload/PollingConfigMapChangeDetector.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/reload/PollingSecretsChangeDetector.java, spring-cloud-kubernetes-fabric8-config/pom.xml, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/reload/ConfigReloadAutoConfiguration.java, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/reload/ConfigReloadDefaultAutoConfiguration.java
=> Remove @EnableAsync On Main

docs/src/main/asciidoc/pod-health-indicator.adoc
=> Add note to disable health indicator in bootstrap yaml | properties

spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/k8s/deployment.yaml, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/reload/EventBasedConfigMapChangeDetector.java, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/reload/EventBasedSecretsChangeDetector.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/k8s/deployment-it.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/k8s/deployment-polling-it.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-loadbalancer-it/k8s/deployment-it.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-reactive-discovery-client-it/k8s/deployment-it.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/deployment-it.yaml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-core-k8s-client-it/k8s/deployment-it.yaml
Fixes #557
Fixes #837
Fixes #831
=> Reconnect Watch For ConfigMaps And Secrets

docs/src/main/asciidoc/property-source-config.adoc, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapPropertySource.java, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapPropertySourceTests.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/AbstractConfigProperties.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/ConfigMapConfigProperties.java, spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/ConfigMapConfigPropertiesTests.java, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigMapPropertySource.java, spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigMapPropertySourceLocator.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/ConfigMapWithPrefixTests.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/with_prefix/App.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/with_prefix/WithPrefixApp.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/with_prefix/controller/Controller.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/with_prefix/properties/One.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/with_prefix/properties/Three.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/with_prefix/properties/Two.java, spring-cloud-kubernetes-fabric8-config/src/test/resources/same-key-with-prefix.yaml
I have only started the work here, so it will stay as Draft for a while
=> fix duplicate properties coming from different config maps

spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/KubernetesClientUtils.java, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientEventBasedConfigMapChangeDetector.java, spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientEventBasedSecretsChangeDetector.java, spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/reload/KubernetesClientConfigReloadAutoConfigurationTest.java, spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/CoreTestClientViaSystemProperties.java, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/skaffold.yaml
=> Pass ApiClient to SharedInformer

spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClient.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClientTests.java
=> Set port name to <unset> in the case the name is null

spring-cloud-kubernetes-client-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/client/loadbalancer/KubernetesClientServicesListSupplier.java
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1130
=> Remove redundant initialization attributes of variables

README.adoc
Fixed Docker mention in README
=> README.adoc link improvements;

spring-cloud-kubernetes-client-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/client/loadbalancer/KubernetesClientLoadBalancerClientConfiguration.java, spring-cloud-kubernetes-fabric8-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/fabric8/loadbalancer/Fabric8LoadBalancerClientConfiguration.java
=> Add caching to load balancer ServiceListSupplier.  

spring-cloud-kubernetes-client-discovery/pom.xml, spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesClientConfigServerBootstrapper.java, spring-cloud-kubernetes-client-discovery/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesClientConfigServerBootstrapperTests.java, spring-cloud-kubernetes-commons/pom.xml, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/KubernetesConfigServerBootstrapper.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/KubernetesConfigServerInstanceProvider.java, spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/KubernetesCommonsAutoConfigurationTests.java, spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/KubernetesBootstrapConfigurationTests.java, spring-cloud-kubernetes-discovery/pom.xml, spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/ConfigServerBootstrapper.java, spring-cloud-kubernetes-discovery/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/ConfigServerBootstrapperTests.java, spring-cloud-kubernetes-fabric8-discovery/pom.xml, spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/Fabric8ConfigServerBootstrapper.java, spring-cloud-kubernetes-fabric8-discovery/src/main/resources/META-INF/spring.factories, spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/Fabric8ConfigServerBootstrapperTests.java
=> Support looking up the config server via DiscoveryClient

docs/src/main/asciidoc/spring-cloud-kubernetes.adoc, spring-cloud-kubernetes-integration-tests/README, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-catalog-watcher/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-configmap-event-reload-multiple-apps/spring-cloud-kubernetes-client-configuration-watcher-configmap-app-a/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-configmap-event-reload-multiple-apps/spring-cloud-kubernetes-client-configuration-watcher-configmap-app-b/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-configmap-event-reload/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-configmap-polling-reload/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-discovery-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-loadbalancer-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-reactive-discoveryclient-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-secrets-event-reload-multiple-apps/spring-cloud-kubernetes-client-configuration-watcher-secrets-app-a/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-secrets-event-reload-multiple-apps/spring-cloud-kubernetes-client-configuration-watcher-secrets-app-b/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-secrets-event-reload/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-core-k8s-client-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-discoveryclient-it/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-catalog-watcher/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-configmap-event-reload/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-configmap-polling-reload/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-configmap/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-discovery-with-bootstrap/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-discovery/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-loadbalancer/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-secrets-event-reload/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-simple-core/pom.xml, spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-istio-it/pom.xml
Added documentation on how to work around ARM64 build
Partially addresses #1155
=> Remove imageBuilder so default is used and can be overwritten on the command line

spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesClientConfigServerBootstrapper.java, spring-cloud-kubernetes-client-discovery/src/test/java/org/springframework/cloud/kubernetes/client/discovery/catalog/KubernetesCatalogWatchAutoConfigurationApplicationContextTests.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/KubernetesNamespaceProvider.java, spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/KubernetesConfigServerBootstrapper.java, spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatchAutoConfigurationTests.java, spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/Fabric8ConfigServerBootstrapper.java, spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesClientServicesFunctionProvider.java, spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesCatalogWatchAutoConfigurationApplicationContextTests.java
This relates to https://github.com/spring-cloud/spring-cloud-config/pull/2375
=> Use propertyresolver revert function

docs/modules/ROOT/pages/spring-cloud-kubernetes-configserver.adoc
Only removing one word, really.
=> Fixing a typo.
